### ISSUE TITLE
Diferença no DV gerando exceção pro SPED-NFE

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-gtin#14]
Ola, na empresa que trabalho usamos o sped-nfe e estamos enfrentando um problema que parece estar neste projeto.

Tem uma NFe com item que possui o seguinte Gtin 7898307879350. Acontece que o validador esta calculando o DV como 10 e dispara exceção pois o código termina com 0. Verifiquei pela calculadora do GS1 (https://www.gs1.org/services/check-digit-calculator#gtin) e o DV do código está correto.

**Comment by robmachado** [comment]
Isso já foi corrigido na ultima atualização
