### ISSUE TITLE
Nova release

### ISSUE THREAD

**Issue by gersonfs** [nfephp-org/sped-gtin#30]
Olá Roberto!

Seria possível lançar uma nova release com a validação de região do Brasil desativada? Vi que no master ela está comentada. Pois na última versão, a v1.0.10 só consigo validar GTIN do Brasil. A NT 2017.001 vai continuar permitindo usar GTIN de outros países, a diferença é que quando forem do Brasil (prefixo 789 e 790) a receita fará uma validação extra, que é a consulta numa base de dados nacional de GTIN.

- Os GTIN's internacionais só precisam atender 1 requisito: ter o DV válido
- Os GTIN's nacionais só precisam atender 2 requisitos: ter o DV válido e constar na base de dados nacional

Pelo menos esse é o meu entendimento.

Seria possível lançar uma v1.0.11 ? 

Estou tendo problemas na validação de alguns códigos de barras.

**Comment by robmachado** [comment]
A questão Gerson é como saber se o GTIN foi cadastrado na base de dados nacional de produtos.
A que eu saiba não tem meios de uma maquina fazer isso.

**Comment by robmachado** [comment]
E complementando você está certo se o GTIN for do Brasil o produto terá de estar cadastrado na base de dados nacional mas os GTINS de fora ainda serão permitidos !

**Comment by gersonfs** [comment]
Sim, esse problema hoje a API não tem como resolver. Fica a cargo do sistema.
Mas o problema hoje é que todos GTIN's que não são do Brasil a API considera inválidos, e isso podemos corrigir.

**Comment by gersonfs** [comment]
> 

Agora vi aqui, eu fiz o update pelo composer para a versão 1.0.10 e essas linhas apareciam **descomentadas**:
https://github.com/nfephp-org/sped-gtin/blob/v1.0.10/src/Gtin.php#L167-L174

Mas aqui no github está comentado... Não entendi, vou rever aqui se atualizei o sistema correto

**Comment by gersonfs** [comment]
Vou fechar para ver aqui, acho que foi algum cache do composer.
