### ISSUE TITLE
Utilização do método consulta junto com sped-nfe

### ISSUE THREAD

**Issue by WilliamSbSis** [nfephp-org/sped-gtin#38]
Estamos tentando instalar esse pacote no mesmo projeto que o pacote sped-nfe.
Precisamos da função de consulta, todavia a mesa está em dev-master.

Isto está gerando um conflito pois o projeto sped-nfe requer o sped-gtin na versão ^1.1.0.

![image](https://user-images.githubusercontent.com/106383617/177837402-3592af58-4fdf-445f-b6ca-e170a286f7c4.png)

Existe alguma previsão  para o lançamento da tag que inclua o método de consulta??

**Comment by robmachado** [comment]
Tag  v1.1.1
